export function usageOverview(state,filter={}) {
  const days=Math.max(1,Math.min(90,Number(filter.days)||30)), cutoff=Date.now()-days*86400000;
  const messages=state.chats.filter(c=>!filter.project||c.projectId===filter.project).flatMap(c=>c.messages.filter(m=>m.role==='assistant'&&Date.parse(m.createdAt)>=cutoff&&(!filter.model||m.model===filter.model)).map(m=>({...m,projectId:c.projectId,chatId:c.id})));
  const daily=new Map(), models=new Map();let input=0,output=0,seconds=0;
  for(let i=days-1;i>=0;i--){const date=new Date(Date.now()-i*86400000).toISOString().slice(0,10);daily.set(date,{date,input:0,output:0,replies:0});}
  for(const m of messages){const i=Math.max(0,Number(m.metrics?.promptTokens)||0),o=Math.max(0,Number(m.metrics?.tokens)||0);input+=i;output+=o;seconds+=Number(m.metrics?.totalSeconds)||0;const date=m.createdAt.slice(0,10),day=daily.get(date);if(day){day.input+=i;day.output+=o;day.replies++;}const row=models.get(m.model)||{model:m.model,input:0,output:0,replies:0};row.input+=i;row.output+=o;row.replies++;models.set(m.model,row);}
  const projects=state.projects.map(p=>{const chats=state.chats.filter(c=>c.projectId===p.id),runs=(state.runs||[]).filter(r=>r.projectId===p.id);return{id:p.id,name:p.name,chats:chats.length,runs:runs.length,changes:(state.changes||[]).filter(c=>c.projectId===p.id).length,lastActivity:chats.map(c=>c.updatedAt||c.createdAt).sort().at(-1)||p.createdAt,active:runs.filter(r=>['running','queued'].includes(r.status)).length};});
  const runs=(state.runs||[]).filter(r=>(!filter.project||r.projectId===filter.project)&&(!filter.model||r.model===filter.model)&&(!filter.status||r.status===filter.status)&&Date.parse(r.createdAt)>=cutoff).slice(-200).reverse().map(({content,events,output,...run})=>({...run,title:String(content||'').slice(0,160)}));
  return{days,input,output,seconds,replies:messages.length,daily:[...daily.values()],models:[...models.values()],projects,runs,note:'Actual Ollama prompt and output counts, summed across tool rounds. Repeated context counts again. Missing metrics are not estimated. Local inference has no per-token bill.'};
}
export function diagnosticReport(state,hardware,prerequisites){return{app:'Local AI Studio',version:'0.2.0',generatedAt:new Date().toISOString(),platform:hardware.platform,arch:hardware.arch,ramGiB:Math.round(hardware.ramGiB),gpus:hardware.gpus.map(g=>({vendor:g.vendor,memoryGiB:g.memoryGiB,confidence:g.confidence})),prerequisites:prerequisites.map(p=>({id:p.id,installed:p.installed,version:p.version})),counts:{projects:state.projects.length,chats:state.chats.length,runs:(state.runs||[]).length,extensions:(state.extensions||[]).length}};}
