import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
test('workflow API enforces scope, model-round budgets, runtime payloads, approved handoff and exact model removal',async()=>{
  const root=path.resolve(import.meta.dirname,'..'),data=fs.mkdtempSync(path.join(root,'test/artifacts/developer-api-')),folder=path.join(data,'source');fs.mkdirSync(folder);fs.writeFileSync(path.join(folder,'README.md'),'Existing project.');let requests=[],deletes=0,mode='loop',installed=true;
  const mock=http.createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;res.setHeader('Content-Type','application/json');if(req.url==='/api/tags')return res.end(JSON.stringify({models:installed?[{name:'small:latest',size:1024,details:{quantization_level:'Q4'}}]:[]}));if(req.url==='/api/ps')return res.end('{"models":[]}');if(req.url==='/api/version')return res.end('{"version":"test"}');const input=JSON.parse(raw||'{}');if(req.url==='/api/generate')return res.end('{}');if(req.url==='/api/show')return res.end('{"capabilities":["completion","tools"],"model_info":{"general.architecture":"test","test.context_length":8192}}');if(req.url==='/api/delete'){assert.equal(req.method,'DELETE');assert.equal(input.model,'small:latest');deletes++;installed=false;return res.end('{}');}assert.equal(req.url,'/api/chat');requests.push(input);const message=mode==='plan'?{content:'Add an accessible contact button.'}:{tool_calls:[{function:{name:'write_project_file',arguments:{path:'README.md',content:'protected overwrite'}}},{function:{name:'write_project_file',arguments:{path:'src/page.js',content:'export const ready = true;'}}}]};res.end(JSON.stringify({message})+'\n'+JSON.stringify({done:true,done_reason:'stop',eval_count:5})+'\n');});mock.listen(0,'127.0.0.1');await once(mock,'listening');const socket=http.createServer();socket.listen(0,'127.0.0.1');await once(socket,'listening');const port=socket.address().port;await new Promise(r=>socket.close(r));
  const child=spawn(process.execPath,[path.join(root,'server.mjs')],{windowsHide:true,stdio:['ignore','pipe','pipe'],env:{...process.env,NODE_ENV:'test',LOCAL_AI_PORT:String(port),LOCAL_AI_OLLAMA_PORT:String(mock.address().port),LOCAL_AI_DATA_DIR:data}});let token,log='';child.stderr.on('data',c=>log+=c);const api=async(route,input,expected=200)=>{const r=await fetch(`http://127.0.0.1:${port}/api${route}`,{method:input===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Local-Token':token},body:input===undefined?undefined:JSON.stringify(input)});const v=await r.json();assert.equal(r.status,expected,JSON.stringify(v));return v;};const until=async(read,done)=>{for(let i=0;i<200;i++){const v=await read();if(done(v))return v;await new Promise(r=>setTimeout(r,25));}throw new Error('Timed out: '+log);};
  try{for(let i=0;i<100;i++){try{token=(await api('/bootstrap')).token;break;}catch{}await new Promise(r=>setTimeout(r,50));}assert.ok(token,log);const p=await api('/projects',{name:'Scoped build',folder},201),route=`/projects/${p.id}/developer`;
    await api(route+'/settings',{editScope:{enabled:true,allowed:['src/**'],protected:[]},runLimits:{minutes:5,rounds:2}});await api('/studio/runtime',{memoryPreset:'eco',compute:'cpu'});const chat=await api('/chats',{projectId:p.id,model:'small:latest',mode:'build'},201),run=await api('/runs',{chatId:chat.id,model:'small:latest',mode:'build',content:'Create a small app.'},202);const result=await until(()=>api('/runs/'+run.id),r=>!['queued','running'].includes(r.run.status));assert.equal(result.run.status,'error');assert.match(result.chat.messages.at(-1).error,/2-round limit/);assert.equal(result.chat.messages.at(-1).limits.roundsUsed,2);assert.equal(fs.readFileSync(path.join(folder,'README.md'),'utf8'),'Existing project.');assert.match(fs.readFileSync(path.join(folder,'src/page.js'),'utf8'),/ready/);assert.equal(requests[0].keep_alive,0);assert.equal(requests[0].options.num_gpu,0);assert.ok(!requests[0].tools.some(t=>/run_project_task|scaffold_project|verify_project|mcp_|generate_project_image/.test(t.function.name)));assert.ok(requests[1].messages.some(m=>m.role==='tool'&&m.content.includes('Edit boundary blocks')));
    mode='plan';const planning=await api('/chats',{projectId:p.id,mode:'plan',model:'small:latest'},201),planRun=await api('/runs',{chatId:planning.id,model:'small:latest',mode:'plan',content:'Plan the contact interaction.'},202),planResult=await until(()=>api('/runs/'+planRun.id),r=>r.run.status==='complete'),message=planResult.chat.messages.at(-1);await api(route+'/handoff',{chatId:planning.id,messageId:message.id,plan:message.content},400);mode='loop';const handoff=await api(route+'/handoff',{chatId:planning.id,messageId:message.id,plan:'Implement the reviewed contact interaction.',approved:true},202);await until(()=>api('/runs/'+handoff.run.id),r=>r.run.status==='error');assert.equal(handoff.chat.handoff.messageId,message.id);assert.equal((await api(route)).chats.length,3);await api(route+'/chat',{id:chat.id,pinned:true,tags:['scope'],archived:true});assert.equal((await api(route)).chats.find(c=>c.id===chat.id).archived,true);
    assert.equal((await api('/studio/model-library')).models[0].size,1024);assert.equal((await api('/studio/model-details',{model:'small:latest'})).modelInfo['test.context_length'],8192);await api('/studio/model-remove',{model:'small:latest',confirm:'small'},400);assert.equal(deletes,0);const removal=await api('/studio/model-remove',{model:'small:latest',confirm:'small:latest'},202);await until(()=>api('/studio/jobs'),jobs=>jobs.find(j=>j.id===removal.id)?.status==='complete');assert.equal(deletes,1);assert.equal((await api('/bootstrap')).models.length,0);assert.equal((await api('/state')).chats.length,3);
  }finally{if(child.exitCode===null){const end=once(child,'exit');child.kill();await end;}await new Promise(r=>mock.close(r));}
});
