import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {DeveloperTools,sourceMap,agentCodeMap,assertEditScope,scopedTool,runtimePolicy,runLimits,deadline,qualityGates} from '../developer-tools.mjs';
import {writeProjectFile} from '../project-files.mjs';
import {verifyProject} from '../project-workbench.mjs';
function fixture(){const folder=fs.mkdtempSync(path.join(os.tmpdir(),'studio-developer-')),p={id:'p',folder,name:'Fixture'},state={projects:[p],chats:[],runs:[],settings:{},preferredModel:'small'};const list=()=>({files:fs.readdirSync(folder,{recursive:true}).filter(f=>fs.statSync(path.join(folder,f)).isFile()).map(f=>({path:f.replaceAll('\\','/'),kind:'text'}))}),read=(p,f)=>({path:f,content:fs.readFileSync(path.join(p.folder,f),'utf8')});let saved=0;const dev=new DeveloperTools(state,()=>saved++,{list,read,write:(p,f,c)=>writeProjectFile(p,f,c,path.join(folder,'.backups')),modelId:m=>{assert.equal(m,'small');return m;},enqueue:input=>{const r={id:'run',...input,status:'queued'};state.runs.push(r);return r;}});return {folder,p,state,dev,list,read,get saved(){return saved;}};}
test('code map resolves explicit local imports, symbols, reverse dependencies and markers',()=>{const f=fixture();fs.writeFileSync(path.join(f.folder,'app.js'),'import {book} from "./booking.js";\n// TODO: Add accessible success state\nfunction start() {}');fs.writeFileSync(path.join(f.folder,'booking.js'),'export function book() {}\n// FIXME: validate date');f.p.contextExcludes=['private.md'];fs.writeFileSync(path.join(f.folder,'private.md'),'TODO private');const map=sourceMap(f.p,f.list,f.read);assert.equal(map.scanned,2);assert.equal(map.nodes.find(n=>n.path==='app.js').imports[0].target,'booking.js');assert.deepEqual(map.nodes.find(n=>n.path==='booking.js').usedBy,['app.js']);assert.deepEqual(map.markers.map(m=>m.line),[2,2]);assert.equal(map.nodes[0].symbols[0].name,'start');});
test('edit boundaries validate atomically, canonicalize paths and protect nested files',()=>{const f=fixture();f.dev.settings(f.p,{editScope:{enabled:true,allowed:['src/**'],protected:['src/locked/**']}});assert.equal(assertEditScope(f.p,'src/page.js'),'src/page.js');assert.throws(()=>assertEditScope(f.p,'index.html'),e=>e.code===403);assert.throws(()=>assertEditScope(f.p,'src/locked/config.js'),e=>e.code===403);assert.throws(()=>assertEditScope(f.p,'src/../outside.js'));assert.equal(scopedTool('run_project_task'),false);assert.equal(scopedTool('mcp_write'),false);assert.equal(scopedTool('move_project_file'),true);const old=JSON.stringify(f.p);assert.throws(()=>f.dev.settings(f.p,{runLimits:{rounds:10,minutes:5},editScope:{enabled:true,allowed:['../bad'],protected:[]}}));assert.equal(JSON.stringify(f.p),old);});
test('literal replacements preserve whitespace, reject stale previews before any write and record backups',()=>{const f=fixture();fs.writeFileSync(path.join(f.folder,'a.js'),'red red ');fs.writeFileSync(path.join(f.folder,'b.js'),'red ');const preview=f.dev.replacePreview(f.p,{find:'red ',replace:'blue '});assert.equal(preview.total,3);fs.writeFileSync(path.join(f.folder,'b.js'),'changed externally');assert.throws(()=>f.dev.replaceApply(f.p,{id:preview.id,confirm:true}),e=>e.code===409);assert.equal(f.read(f.p,'a.js').content,'red red ');fs.writeFileSync(path.join(f.folder,'b.js'),'red ');const result=f.dev.replaceApply(f.p,{id:preview.id,confirm:true});assert.equal(result.files.length,2);assert.equal(f.read(f.p,'a.js').content,'blue blue ');assert.ok(result.files.every(i=>i.backup));assert.throws(()=>f.dev.replaceApply(f.p,{id:preview.id,confirm:true}),e=>e.code===409);});
test('replacement rolls back earlier writes without overwriting a concurrent external change',()=>{const f=fixture();fs.writeFileSync(path.join(f.folder,'a.js'),'red');fs.writeFileSync(path.join(f.folder,'b.js'),'red');const preview=f.dev.replacePreview(f.p,{find:'red',replace:'blue'}),write=f.dev.deps.write;f.dev.deps.write=(p,file,content)=>{if(file==='b.js')throw new Error('disk failed');return write(p,file,content);};assert.throws(()=>f.dev.replaceApply(f.p,{id:preview.id,confirm:true}),/restored/);assert.equal(f.read(f.p,'a.js').content,'red');assert.equal(f.read(f.p,'b.js').content,'red');});
test('quality scripts run in order and stop at the first actual failure',async()=>{const f=fixture();fs.writeFileSync(path.join(f.folder,'package.json'),JSON.stringify({scripts:{lint:'node lint.cjs',test:'node test.cjs',build:'node build.cjs'}}));fs.writeFileSync(path.join(f.folder,'lint.cjs'),'require("node:fs").appendFileSync("order.txt","lint\\n");');fs.writeFileSync(path.join(f.folder,'test.cjs'),'require("node:fs").appendFileSync("order.txt","test\\n");process.exitCode=1;');fs.writeFileSync(path.join(f.folder,'build.cjs'),'require("node:fs").appendFileSync("order.txt","build\\n");');f.dev.settings(f.p,{qualityScripts:['lint','test','build']});const result=await verifyProject(f.p,f.list,f.read,new AbortController().signal);assert.equal(result.success,false);assert.deepEqual(result.checks.slice(1).map(c=>c.name),['lint','test']);assert.equal(f.read(f.p,'order.txt').content,'lint\ntest\n');const blocked=await qualityGates({...f.p,allowCommands:false},undefined);assert.equal(blocked.success,false);assert.equal(blocked.checks[0].skipped,true);});
test('approved handoff records provenance and creates a genuine queued Build without changing Plan history',()=>{const f=fixture(),source={id:'chat',projectId:'p',title:'Booking plan',model:'small',messages:[{id:'message',role:'assistant',mode:'plan',status:'complete',content:'Add a form.'}]};f.state.chats.push(source);assert.throws(()=>f.dev.handoff(f.p,{chatId:'chat',messageId:'message',plan:'Add a form.'}),/approve/);const result=f.dev.handoff(f.p,{chatId:'chat',messageId:'message',approved:true,plan:'Add and validate the form.'});assert.equal(result.run.mode,'build');assert.match(result.run.content,/validate/);assert.equal(result.chat.handoff.messageId,'message');assert.equal(result.chat.handoff.sha256.length,64);assert.equal(source.messages.length,1);});
test('chat pins, tags and archive are persistent metadata with running-request protection',()=>{const f=fixture();f.state.chats.push({id:'c',projectId:'p',messages:[]});f.dev.chat(f.p,{id:'c',pinned:true,tags:['booking','booking'],archived:true});assert.deepEqual(f.state.chats[0].tags,['booking']);assert.equal(f.state.chats[0].archived,true);f.state.runs.push({chatId:'c',status:'queued'});assert.throws(()=>f.dev.chat(f.p,{id:'c',archived:false}),e=>e.code===409);assert.equal(f.state.chats[0].archived,true);});
test('memory policy, run limits and deadline produce actual execution controls',async()=>{assert.deepEqual(runtimePolicy({memoryPreset:'eco',compute:'cpu'}),{keep_alive:0,options:{num_gpu:0}});assert.equal(runtimePolicy({memoryPreset:'warm'}).keep_alive,'10m');assert.deepEqual(runLimits({}),{rounds:0,minutes:0});assert.deepEqual(runLimits({runLimits:{rounds:80,minutes:5}}),{rounds:80,minutes:5});const c=new AbortController(),clear=deadline(c,0.00001);await new Promise(r=>setTimeout(r,10));assert.equal(c.signal.aborted,true);assert.match(c.signal.reason.message,/time limit/);clear();});
test('agent map bounds serialized context and reports omitted files',()=>{const f=fixture();for(let i=0;i<100;i++)fs.writeFileSync(path.join(f.folder,'source-'+i+'.js'),Array.from({length:20},(_,n)=>'export function longSymbolName'+n+'() {}').join('\n'));const map=agentCodeMap(f.p,f.list,f.read);assert.ok(JSON.stringify(map).length<=12000);assert.equal(map.scanned,100);assert.equal(map.truncated,true);assert.ok(map.nodes.length>0&&map.nodes.length<100);});
